bimbel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('dash/', include('bimbel_app.urls')),
]
urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bimbel_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import base_views
from .views import master_views
from .views import kesiswaan_views
from .views import ujian_views
from .views import materi_views
from .views import guru_views
from .views import announce_views
# from .views import penimbangan_views
# from .views import nota_views

app_name = 'bimbel_app'
urlpatterns = [
    path('', base_views.IndexView.as_view(), name = 'index'),
    path('login/', base_views.LoginView.as_view(), name = 'login'),
    path('logout/', base_views.LogoutView.as_view(), name = 'logout'),
    path('pengaturan/aplikasi/', base_views.setting_aplikasiView.as_view(), name = 'setting_aplikasi'),
    # path('join_video_conf/', base_views.join_video_confView.as_view(), name = 'join_video_conf'),
    path('master/usermanagement/', master_views.UsermanagementView.as_view(), name = 'usermanagement'),
    path('master/usermanagement/edit/<str:uid>/', master_views.UsermanagementEditView.as_view(), name = 'usermanagementedit'),
    path('master/usermanagement/delete/<str:uid>/', master_views.UsermanagementDeleteView.as_view(), name = 'usermanagementdelete'),

    path('master/mapel/', master_views.MapelView.as_view(), name = 'mapel'),
    path('master/mapel/edit/<str:kode_mapel>/', master_views.MapelEditView.as_view(), name = 'mapeledit'),
    path('master/mapel/delete/<str:kode_mapel>/', master_views.MapelDeleteView.as_view(), name = 'mapeldelete'),

    path('master/kelas/', master_views.KelasView.as_view(), name = 'kelas'),
    path('master/kelas/edit/<str:kode_kelas>/', master_views.KelasEditView.as_view(), name = 'kelasedit'),
    path('master/kelas/delete/<str:kode_kelas>/', master_views.KelasDeleteView.as_view(), name = 'kelasdelete'),

    path('master/kategori-ujian/', master_views.kategori_ujianView.as_view(), name = 'kategori_ujian'),
    path('master/kategori_ujian/edit/<str:kode_ujian>/', master_views.kategori_ujianEditView.as_view(), name = 'kategori_ujianedit'),
    path('master/kategori_ujian/delete/<str:kode_ujian>/', master_views.kategori_ujianDeleteView.as_view(), name = 'kategori_ujiandelete'),

    path('kesiswaan/pesertadidik/', kesiswaan_views.PesertaDidikView.as_view(), name = 'pesertadidik'),
    path('kesiswaan/pesertadidik/<str:type_>/<int:uid>/', kesiswaan_views.tambah_siswaView.as_view(), name = 'tambah_siswa'),
    path('kesiswaan/profil-pesertadidik/<str:type_>/<str:uid>/', kesiswaan_views.profil_siswaView.as_view(), name = 'profil_siswa'),
    path('kesiswaan/pesertadidik/<int:uid>/', kesiswaan_views.DeleteSiswaViews.as_view(), name = 'hapus_siswa'),
    path('kesiswaan/pesertadidik/validation/access-login/vali_log/', kesiswaan_views.ValidationLoginSiswaViews.as_view(), name = 'vali_log'),

    path('pengajar/guru/', guru_views.guruView.as_view(), name = 'guru'),
    path('pengajar/guru/<str:type_>/<int:uid>/', guru_views.tambah_guruView.as_view(), name = 'tambah_guru'),

    path('pengajar/profil-guru/<str:type_>/<str:uid>/', guru_views.profil_guruView.as_view(), name = 'profil_guru'),

    path('ujian/list_ujian/', ujian_views.List_ujianView.as_view(), name = 'list_ujian'),
    path('ujian/list_ujian/add_edit/<str:type_>/<str:uid>/', ujian_views.tambah_ujianView.as_view(), name = 'tambah_ujian'),
    path('ujian/list_ujian/delete/<str:uid>/', ujian_views.DeleteListUjianViews.as_view(), name = 'list_ujiandelete'),
    path('ujian/list_ujian/manajemen_soal/<str:uid>/', ujian_views.manajemen_soal_ujianView.as_view(), name = 'manajemen_soal_ujian'),
    path('ujian/list_ujian/upload_image_soal/', ujian_views.upload_image_soalViews.as_view(), name = 'upload_image_soal'),
    path('ujian/list_ujian/get_soal/', ujian_views.get_soalViews.as_view(), name = 'get_soal'),
    path('ujian/list_ujian/assignment/<str:id_ujian>/', ujian_views.kerjakan_soalViews.as_view(), name = 'kerjakan_soal'),
    path('ujian/list_ujian/get_soal_/', ujian_views.get_soaldankunciViews.as_view(), name = 'get_soaldankunci'),
    path('ujian/list_ujian/check_jawaban/', ujian_views.check_jawabanViews.as_view(), name = 'check_jawaban'),
    path('ujian/list_ujian/force_empty/', ujian_views.force_emptyViews.as_view(), name = 'force_empty'),
    path('ujian/lihat_hasil/<str:id_ujian>/', ujian_views.Lihat_hasilViews.as_view(), name = 'lihat_hasil'),
    path('ujian/change_stat_ujian/<str:status_>/', ujian_views.change_stat_ujianView.as_view(), name = 'change_stat_ujian'),
    path('ujian/peserta_ujian/<str:id_ujian>/', ujian_views.peserta_ujianView.as_view(), name = 'peserta_ujian'),

    path('materi/list_materi/', materi_views.List_materiView.as_view(), name = 'list_materi'),
    path('materi/create_materi/', materi_views.Create_materiView.as_view(), name = 'create_materi'),
    path('materi/change_stat_materi/<str:status_>/', materi_views.change_stat_materiView.as_view(), name = 'change_stat_materi'),
    path('materi/del_materi/', materi_views.del_materiView.as_view(), name = 'del_materi'),
    path('materi/edit_materi/<str:id_materi>/', materi_views.Edit_materiView.as_view(), name = 'edit_materi'),
    path('materi/del_fileView/', materi_views.del_fileView.as_view(), name = 'del_file'),
    path('materi/lihat_materi/<str:id_materi>/', materi_views.lihat_materiView.as_view(), name = 'lihat_materi'),
    
    path('pengumuman/daftar_pengumuman/', announce_views.list_announceViews.as_view(), name = 'list_announce'),
    path('pengumuman/create_pengumuman/', announce_views.Create_pengumumanView.as_view(), name = 'create_pengumuman'),
    path('pengumuman/edit_pengumuman/<str:id_pengumuman>/', announce_views.Edit_pengumumanView.as_view(), name = 'edit_pengumuman'),
    path('pengumuman/del_fileView/', announce_views.del_file_pengumumanView.as_view(), name = 'del_file_pengumuman'),
    path('pengumuman/change_stat_pengumuman/<str:status_>/', announce_views.change_stat_pengumumanView.as_view(), name = 'change_stat_pengumuman'),
    path('pengumuman/lihat_pengumuman/<str:id_pengumuman>/', announce_views.lihat_pengumumanView.as_view(), name = 'lihat_pengumuman'),
    path('pengumuman/del_pengumuman/', announce_views.del_pengumumanView.as_view(), name = 'del_pengumuman'),
] 

bimbel_app/models/master.py
from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField

class Master_user(models.Model):
    uid = models.AutoField(blank=False, null=False, primary_key=True)
    uname = models.TextField(blank=False, null=False)
    pwd = models.TextField(blank=False, null=False)
    fullname = models.TextField(blank=False, null=False)
    nip = models.TextField(blank=False, null=False)
    level = models.TextField(blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        managed = False
        db_table = 'master\".\"master_user'
        ordering = ['uname']

class Master_mata_pelajaran(models.Model):
    kode_mapel = models.TextField(blank=False, null=False, primary_key=True)
    nama_mapel = models.TextField(blank=False, null=False)
    user_input = models.ForeignKey(Master_user, on_delete=models.PROTECT, db_column='user_input')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        managed = False
        db_table = 'master\".\"master_mata_pelajaran'
        ordering = ['kode_mapel']

class Master_kelas(models.Model):
    kode_kelas = models.TextField(blank=False, null=False, primary_key=True)
    nama_kelas = models.TextField(blank=False, null=False)
    user_input = models.ForeignKey(Master_user, on_delete=models.PROTECT, db_column='user_input')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        managed = False
        db_table = 'master\".\"master_kelas'
        ordering = ['kode_kelas']

class Master_ujian(models.Model):
    kode_ujian = models.TextField(blank=False, null=False, primary_key=True)
    nama_ujian = models.TextField(blank=False, null=False)
    user_input = models.ForeignKey(Master_user, on_delete=models.PROTECT, db_column='user_input')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        managed = False
        db_table = 'master\".\"master_ujian'
        ordering = ['kode_ujian']


class Peserta_didik(models.Model):
    uid = models.AutoField(blank=False, null=False, primary_key=True)
    nama_siswa = models.TextField(blank=False, null=False)
    nis = models.TextField(blank=False, null=False)
    kelas = models.ForeignKey(Master_kelas, on_delete=models.PROTECT, db_column='kelas')
    jenis_kelamin = models.CharField(blank=False, null=False, max_length = 1)
    tempat_lahir = models.TextField(blank=False, null=False)
    tanggal_lahir = models.DateField()
    alamat = models.TextField(blank=False, null=False)
    agama = models.TextField(blank=False, null=False)
    no_hp = models.TextField(blank=False, null=False)
    tahun_registrasi = models.CharField(blank=False, null=False, max_length = 4)
    status = models.CharField(blank=False, null=False, max_length = 1)
    informasi_lain = models.TextField(blank=False, null=False)
    foto = models.TextField(blank=False, null=False)
    email = models.TextField(blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_input = models.ForeignKey(Master_user, on_delete=models.PROTECT, db_column='user_input')

    class Meta:
        managed = False
        db_table = 'kesiswaan\".\"peserta_didik'
        ordering = ['uid']

class Master_guru(models.Model):
    uid = models.AutoField(blank=False, null=False, primary_key=True)
    nama_guru = models.TextField(blank=False, null=False)
    nip = models.TextField(blank=False, null=False)
    jenis_kelamin = models.CharField(blank=False, null=False, max_length = 1)
    tempat_lahir = models.TextField(blank=False, null=False)
    tanggal_lahir = models.DateField()
    alamat = models.TextField(blank=False, null=False)
    agama = models.TextField(blank=False, null=False)
    no_hp = models.TextField(blank=False, null=False)
    tahun_registrasi = models.CharField(blank=False, null=False, max_length = 4)
    status = models.CharField(blank=False, null=False, max_length = 1)
    informasi_lain = models.TextField(blank=False, null=False)
    foto = models.TextField(blank=False, null=False)
    email = models.TextField(blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_input = models.ForeignKey(Master_user, on_delete=models.PROTECT, db_column='user_input')

    class Meta:
        managed = False
        db_table = 'kesiswaan\".\"guru'
        ordering = ['uid']

class List_ujian(models.Model):
    id_ujian = models.AutoField(blank=False, null=False, primary_key=True)
    judul = models.TextField(blank=False, null=False)
    kategori = models.ForeignKey(Master_ujian, on_delete=models.PROTECT, db_column='kategori')
    mata_pelajaran = models.ForeignKey(Master_mata_pelajaran, on_delete=models.PROTECT, db_column='mata_pelajaran')
    kelas = models.CharField(blank=False, null=False, max_length = 1)
    daftar_kelas = ArrayField(models.CharField(max_length=200),size=1)
    durasi = models.IntegerField(blank=False, null=False)
    durasi_minimal = models.IntegerField(blank=False, null=False)
    urutan_soal = models.CharField(blank=False, null=False, max_length = 1)
    jml_soal_tampil = models.IntegerField(blank=False, null=False)
    tgl_terbit_auto = models.DateTimeField()
    tgl_tutup_auto = models.DateTimeField()
    tampilkan_nilai = models.TextField(blank=False, null=False)
    tampilkan_jawaban = models.TextField(blank=False, null=False)
    pwd = models.TextField(blank=False, null=False)
    user_input = models.ForeignKey(Master_user, on_delete=models.PROTECT, db_column='user_input')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.TextField(blank=False, null=False)
    deskripsi = models.TextField(blank=False, null=False)
    kkm = models.FloatField(blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'ujian\".\"list_ujian'
        ordering = ['id_ujian']

class Manajemen_soal(models.Model):
    id_soal = models.AutoField(blank=False, null=False, primary_key=True)
    kode_ujian = models.ForeignKey(List_ujian, on_delete=models.PROTECT, db_column='kode_ujian')
    no_soal = models.IntegerField(blank=False, null=False)
    uraian_soal = models.TextField(blank=False, null=False)
    jawaban1 = models.TextField(blank=False, null=False)
    jawaban2 = models.TextField(blank=False, null=False)
    jawaban3 = models.TextField(blank=False, null=False)
    jawaban4 = models.TextField(blank=False, null=False)
    jawaban5 = models.TextField(blank=False, null=False)
    kunci_jawaban = models.CharField(blank=False, null=False, max_length = 1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_input = models.ForeignKey(Master_user, on_delete=models.PROTECT, db_column='user_input')

    class Meta:
        managed = False
        db_table = 'ujian\".\"manajemen_soal'
        ordering = ['id_soal']

class Jawaban_soal(models.Model):
    id_ujian = models.OneToOneField(List_ujian, on_delete=models.PROTECT, db_column='id_ujian', unique=True,  primary_key=True)
    id_soal = models.OneToOneField(Manajemen_soal, on_delete=models.PROTECT, db_column='id_soal', unique = True)
    jawaban = models.CharField(blank=False, null=False, max_length = 1)
    id_pd = models.OneToOneField(Peserta_didik, on_delete=models.PROTECT, db_column='id_pd', unique = True)
    tgl_input = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_input = models.ForeignKey(Master_user, on_delete=models.PROTECT, db_column='user_input')

    class Meta:
        managed = False
        db_table = 'ujian\".\"jawaban_soal'
        ordering = ['id_ujian']

class Siswa_assignment(models.Model):
    id_siswa_assignment = models.AutoField(blank=False, null=False, primary_key=True)
    id_ujian = models.ForeignKey(List_ujian, on_delete=models.PROTECT, db_column='id_ujian')
    id_pd = models.ForeignKey(Peserta_didik, on_delete=models.PROTECT, db_column='id_pd')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_input = models.ForeignKey(Master_user, on_delete=models.PROTECT, db_column='user_input')
    status = models.TextField(blank=False, null=False)
    nilai = models.DecimalField(blank=False, null=False, decimal_places = 2, max_digits = 4)

    class Meta:
        managed = False
        db_table = 'ujian\".\"siswa_assignment'
        ordering = ['id_siswa_assignment']


class List_materi(models.Model):
    id_materi = models.AutoField(blank=False, null=False, primary_key=True)
    judul = models.TextField(blank=False, null=False)
    isi_materi = models.TextField(blank=False, null=False)
    mata_pelajaran = models.ForeignKey(Master_mata_pelajaran, on_delete=models.PROTECT, db_column='mata_pelajaran')
    kelas = models.TextField(blank=False, null=False)
    daftar_kelas = ArrayField(models.TextField(max_length=200),size=1)
    status = models.TextField(blank=False, null=False)
    file_support = ArrayField(models.TextField(max_length=1000),size=1)
    user_input = models.ForeignKey(Master_user, on_delete=models.PROTECT, db_column='user_input')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    count_see = models.IntegerField(blank=False, null=False)

    class Meta:
        managed = False
        db_table = 'materi\".\"list_materi'
        ordering = ['id_materi']

class List_pengumuman(models.Model):
    id_pengumuman = models.AutoField(blank=False, null=False, primary_key=True)

bimbel_app/templates/kesiswaan/pesertadidik.html
{% extends 'base/index.html' %}
{% load static %}

{% block content %}

<div class="row">
	<div class="col-12">
		<div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Peserta Didik <button class="btn btn-md btn-primary" onclick="showModal(this,'peserta_didik','add')" alt="{% url 'bimbel_app:tambah_siswa' 'add' 0 %}">Tambah Siswa</button></h4>
			</div>
			<div class="box-body">
			  <div class="table-responsive">
				  <table id="table_user" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
					<thead>
						<tr>
							<th class="width_nomor_tabel">NO</th>
							<th class="width_nomor_tabel">NO. REGISTRASI</th>
							<th>NAMA</th>
							<th class="width_nomor_tabel">KELAS</th>
							<th class="width_nomor_tabel"></th>
						</tr>
					</thead>
					<tbody>
						{% for x in data_siswa %}
							<tr>
								<td class="td_center">{{forloop.counter}}</td>
								<td class="td_center">{{x.uid}}</td>
								<td><img src="{% static 'images/f_profil/'%}{{x.foto}}" class="avatar avatar-lg rounded10 bg-primary-light" alt=""> {{x.nama_siswa.title}}</td>
								<td class="td_center">{{x.kelas.nama_kelas}}</td>
								<td class="td_center">
									<button class="btn btn-rounded btn-info btn-xs" onclick="showModal(this,'peserta_didik','edit')" alt="{% url 'bimbel_app:tambah_siswa' 'edit' x.uid %}" id="btn_edit_user" data-u="{{x.nama_siswa}}" data-id="{{x.uid}}"><i class="fa fa-pencil"></i></button>
									<button class="btn btn-rounded btn-danger btn-xs" onclick="delete_siswa(this)" id="btn_del_user" data-u="{{x.nama_siswa}}" data-id="{{x.uid}}" del_url="{% url 'bimbel_app:hapus_siswa' x.uid %}"><i class="fa fa-trash"></i></button>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				</div>       
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
	$(document).ready(function(){
		$('#table_user').DataTable( {
		dom: 'Bfrtip',
		buttons: [
			'excel', 'pdf'
		]
	} );

		
	})

	function edit_mapel(e){
		$.ajax({
            type: "GET",
            // headers: { "X-CSRFToken": csrf_token },
            url: $(e).attr('edit_url'),
            data: {'kode_mapel':$(e).attr('data-id')},
            dataType: 'json',
            success: function(res){
            	data = res['data_mapel'][0];
            	$('#id_nama_mapel').val(data['nama_mapel']);
            	$('#id_kode_mapel').val('s');
            	$('#kode_mapel_div').css('display', 'none');
            	$('#cancel_edit').css('display', '');
            	$('#frm_mapel').attr('action', $(e).attr('edit_url'))
            },
            error: function(res){
                msg_pesan('Hapus Item Gagal. ','error');
                $('#frm_mapel').attr('action', "{% url 'bimbel_app:mapel' %}");
                $('#cancel_edit').css('display', 'none');
            }
        });
	};

	function delete_siswa(e){
		Swal.fire({
              title: 'Yakin mau menghapus \"'+$(e).attr('data-u')+'\" ?',
              icon: 'warning',
              showCancelButton: true,
              confirmButtonColor: '#3085d6',
              cancelButtonColor: '#d33',
              confirmButtonText: 'Hapus'
            }).then((result) => {
              if (result.isConfirmed) {
                $.ajax({
                    type: "POST",
                    headers: { "X-CSRFToken": csrf_token },
                    url: $(e).attr('del_url'),
                    data: {'uid':$(e).attr('data-id')},
                    dataType: 'json',
                    success: function(res){
                        if (res['status']) {
                            msg_pesan('Hapus Siswa Sukses. ','success');
                            location.reload();
                        }else{
                            msg_pesan('Hapus Siswa Gagal. ','error');
                        }
                    },
                    error: function(res){
                        msg_pesan('Hapus Siswa Gagal. ','error');
                    }
                });
              }
            });
	};
</script>
{% endblock %}