bimbel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('dash/', include('bimbel_app.urls')),
]
urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bimbel_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import base_views
from .views import master_views
from .views import kesiswaan_views
from .views import ujian_views
from .views import materi_views
from .views import guru_views
from .views import announce_views
# from .views import penimbangan_views
# from .views import nota_views

app_name = 'bimbel_app'
urlpatterns = [
    path('', base_views.IndexView.as_view(), name = 'index'),
    path('login/', base_views.LoginView.as_view(), name = 'login'),
    path('logout/', base_views.LogoutView.as_view(), name = 'logout'),
    path('pengaturan/aplikasi/', base_views.setting_aplikasiView.as_view(), name = 'setting_aplikasi'),
    # path('join_video_conf/', base_views.join_video_confView.as_view(), name = 'join_video_conf'),
    path('master/usermanagement/', master_views.UsermanagementView.as_view(), name = 'usermanagement'),
    path('master/usermanagement/edit/<str:uid>/', master_views.UsermanagementEditView.as_view(), name = 'usermanagementedit'),
    path('master/usermanagement/delete/<str:uid>/', master_views.UsermanagementDeleteView.as_view(), name = 'usermanagementdelete'),

    path('master/mapel/', master_views.MapelView.as_view(), name = 'mapel'),
    path('master/mapel/edit/<str:kode_mapel>/', master_views.MapelEditView.as_view(), name = 'mapeledit'),
    path('master/mapel/delete/<str:kode_mapel>/', master_views.MapelDeleteView.as_view(), name = 'mapeldelete'),

    path('master/kelas/', master_views.KelasView.as_view(), name = 'kelas'),
    path('master/kelas/edit/<str:kode_kelas>/', master_views.KelasEditView.as_view(), name = 'kelasedit'),
    path('master/kelas/delete/<str:kode_kelas>/', master_views.KelasDeleteView.as_view(), name = 'kelasdelete'),

    path('master/kategori-ujian/', master_views.kategori_ujianView.as_view(), name = 'kategori_ujian'),
    path('master/kategori_ujian/edit/<str:kode_ujian>/', master_views.kategori_ujianEditView.as_view(), name = 'kategori_ujianedit'),
    path('master/kategori_ujian/delete/<str:kode_ujian>/', master_views.kategori_ujianDeleteView.as_view(), name = 'kategori_ujiandelete'),

    path('kesiswaan/pesertadidik/', kesiswaan_views.PesertaDidikView.as_view(), name = 'pesertadidik'),
    path('kesiswaan/pesertadidik/<str:type_>/<int:uid>/', kesiswaan_views.tambah_siswaView.as_view(), name = 'tambah_siswa'),
    path('kesiswaan/profil-pesertadidik/<str:type_>/<str:uid>/', kesiswaan_views.profil_siswaView.as_view(), name = 'profil_siswa'),
    path('kesiswaan/pesertadidik/<int:uid>/', kesiswaan_views.DeleteSiswaViews.as_view(), name = 'hapus_siswa'),
    path('kesiswaan/pesertadidik/validation/access-login/vali_log/', kesiswaan_views.ValidationLoginSiswaViews.as_view(), name = 'vali_log'),

    path('pengajar/guru/', guru_views.guruView.as_view(), name = 'guru'),
    path('pengajar/guru/<str:type_>/<int:uid>/', guru_views.tambah_guruView.as_view(), name = 'tambah_guru'),

    path('pengajar/profil-guru/<str:type_>/<str:uid>/', guru_views.profil_guruView.as_view(), name = 'profil_guru'),

    path('ujian/list_ujian/', ujian_views.List_ujianView.as_view(), name = 'list_ujian'),
    path('ujian/list_ujian/add_edit/<str:type_>/<str:uid>/', ujian_views.tambah_ujianView.as_view(), name = 'tambah_ujian'),
    path('ujian/list_ujian/delete/<str:uid>/', ujian_views.DeleteListUjianViews.as_view(), name = 'list_ujiandelete'),
    path('ujian/list_ujian/manajemen_soal/<str:uid>/', ujian_views.manajemen_soal_ujianView.as_view(), name = 'manajemen_soal_ujian'),
    path('ujian/list_ujian/upload_image_soal/', ujian_views.upload_image_soalViews.as_view(), name = 'upload_image_soal'),
    path('ujian/list_ujian/get_soal/', ujian_views.get_soalViews.as_view(), name = 'get_soal'),
    path('ujian/list_ujian/assignment/<str:id_ujian>/', ujian_views.kerjakan_soalViews.as_view(), name = 'kerjakan_soal'),
    path('ujian/list_ujian/get_soal_/', ujian_views.get_soaldankunciViews.as_view(), name = 'get_soaldankunci'),
    path('ujian/list_ujian/check_jawaban/', ujian_views.check_jawabanViews.as_view(), name = 'check_jawaban'),
    path('ujian/list_ujian/force_empty/', ujian_views.force_emptyViews.as_view(), name = 'force_empty'),
    path('ujian/lihat_hasil/<str:id_ujian>/', ujian_views.Lihat_hasilViews.as_view(), name = 'lihat_hasil'),
    path('ujian/change_stat_ujian/<str:status_>/', ujian_views.change_stat_ujianView.as_view(), name = 'change_stat_ujian'),
    path('ujian/peserta_ujian/<str:id_ujian>/', ujian_views.peserta_ujianView.as_view(), name = 'peserta_ujian'),

    path('materi/list_materi/', materi_views.List_materiView.as_view(), name = 'list_materi'),
    path('materi/create_materi/', materi_views.Create_materiView.as_view(), name = 'create_materi'),
    path('materi/change_stat_materi/<str:status_>/', materi_views.change_stat_materiView.as_view(), name = 'change_stat_materi'),
    path('materi/del_materi/', materi_views.del_materiView.as_view(), name = 'del_materi'),
    path('materi/edit_materi/<str:id_materi>/', materi_views.Edit_materiView.as_view(), name = 'edit_materi'),
    path('materi/del_fileView/', materi_views.del_fileView.as_view(), name = 'del_file'),
    path('materi/lihat_materi/<str:id_materi>/', materi_views.lihat_materiView.as_view(), name = 'lihat_materi'),
    
    path('pengumuman/daftar_pengumuman/', announce_views.list_announceViews.as_view(), name = 'list_announce'),
    path('pengumuman/create_pengumuman/', announce_views.Create_pengumumanView.as_view(), name = 'create_pengumuman'),
    path('pengumuman/edit_pengumuman/<str:id_pengumuman>/', announce_views.Edit_pengumumanView.as_view(), name = 'edit_pengumuman'),
    path('pengumuman/del_fileView/', announce_views.del_file_pengumumanView.as_view(), name = 'del_file_pengumuman'),
    path('pengumuman/change_stat_pengumuman/<str:status_>/', announce_views.change_stat_pengumumanView.as_view(), name = 'change_stat_pengumuman'),
    path('pengumuman/lihat_pengumuman/<str:id_pengumuman>/', announce_views.lihat_pengumumanView.as_view(), name = 'lihat_pengumuman'),
    path('pengumuman/del_pengumuman/', announce_views.del_pengumumanView.as_view(), name = 'del_pengumuman'),
] 

bimbel_app/views/announce_views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
import json, os, requests
from django.contrib import messages
from bimbel_app.models.master import (Master_user as m_user, Master_mata_pelajaran as m_mapel, Peserta_didik as m_pd, 
                                        Master_kelas as m_kelas, List_ujian as m_listujian, Master_ujian as m_ujian, Manajemen_soal as m_soal,
                                        Jawaban_soal as j_soal, Siswa_assignment as s_assignment, List_materi as m_listmateri,
                                        List_pengumuman as m_listpengumuman)
from django.forms import *
from support.support_function import decrypt, encrypt, global_var, random_string_angka
from bimbel.settings import BASE_DIR, DBX_TOKEN
import re
from datetime import datetime
from django.db.models import Q
from django.template import RequestContext
import dropbox
from django.urls import reverse
from bimbel_app.views.ujian_views import Helper

class list_announceViews(View):
    """docstring for List_ujianView"""
    def get(self, request):
        if global_var(request)['level'] == 'GURU':
            data_pengumuman = m_listpengumuman.objects.filter(user_input = global_var(request)['uid'])
        elif global_var(request)['level'] == 'ADMIN':
            data_pengumuman = m_listpengumuman.objects.all()
        else:
            data_pengumuman = ''
        data = {
            'data_pengumuman':data_pengumuman,
        }
        return render(request, 'announce/list_pengumuman.html', data)

class Create_pengumumanView(View):
    """docstring for Create_materiView"""
    def get(self, request):
        data_kelas = m_kelas.objects.all()
        data_jenis_ujian = m_ujian.objects.all()
        data_mapel = m_mapel.objects.all()
        data_list_ujian = ''
        data_login = ''
        uuid = 0
        
        data = {
            'data_kelas':data_kelas,
            # 'type_':type_, 
            'data_list_ujian':data_list_ujian,
            'data_login':data_login,
            # 'uuid':uid,
            'data_jenis_ujian':data_jenis_ujian,
            'data_mapel':data_mapel,
            'link':reverse('bimbel_app:create_pengumuman'),
        }
        return render(request, 'announce/create_pengumuman.html', data)

    def post(self, request):
        judul = request.POST.get('judul')
        tgl_terbit = request.POST.get('tgl_terbit')
        file = request.FILES.getlist('filenya')
        isi_materi = request.POST.get('isi_materi')
        arr_file = []

        tgl_terbit_ = datetime.strptime(tgl_terbit.split(' - ')[0], '%d/%m/%Y %H:%M')
        tgl_tutup = datetime.strptime(tgl_terbit.split(' - ')[1], '%d/%m/%Y %H:%M')


        for upload_file in file:
            rand_name = re.sub('[^\w\-_\. ]', '_', encrypt(str(datetime.now())))+random_string_angka()+' - '+upload_file.name.replace(' ','')

            file_path_ = os.path.join(BASE_DIR, 'bimbel_app', 'assets', 'doc_materi_temp', rand_name)
            with open(file_path_, 'wb+') as destination:
                for chunk in upload_file.chunks():
                    destination.write(chunk)

            dbx = dropbox.Dropbox(DBX_TOKEN)
            dbx.users_get_current_account()
            with open(file_path_, 'rb') as destination:
                dbx.files_upload(bytes(destination.read()), '/pengumuman/{}'.format(rand_name))
            arr_file.append(rand_name)
            os.remove(file_path_)

        pengumuman = m_listpengumuman(
                judul = judul,
                isi_materi = isi_materi,
                status = 'TERBIT',
                tgl_terbit_auto = tgl_terbit_,
                tgl_tutup_auto = tgl_tutup,
                file_support = arr_file,
                user_input = m_user.objects.get(uid=global_var(request)['uid']),
                count_see = 0,
            )
        pengumuman.save()

        last_id_ = m_listpengumuman.objects.latest('id_pengumuman')

        return redirect('bimbel_app:edit_pengumuman', id_pengumuman=encrypt(str(last_id_.id_pengumuman)))

class Edit_pengumumanView(View):
    """docstring for Create_materiView"""
    def get(self, request, id_pengumuman):
        id_pengumuman = decrypt(id_pengumuman)
        data_kelas = m_kelas.objects.all()
        data_jenis_ujian = m_ujian.objects.all()
        data_mapel = m_mapel.objects.all()
        data_pengumuman = m_listpengumuman.objects.get(id_pengumuman = id_pengumuman)
        data_list_ujian = ''
        data_login = ''
        uuid = 0
        
        data = {
            'data_kelas':data_kelas,
            'type_':'edit', 
            'data_list_ujian':data_list_ujian,
            'data_login':data_login,
            # 'uuid':uid,
            'data_jenis_ujian':data_jenis_ujian,
            'data_mapel':data_mapel,
            'data_pengumuman':data_pengumuman,
            'link':reverse('bimbel_app:edit_pengumuman', args=(encrypt(id_pengumuman),)),
        }
        return render(request, 'announce/create_pengumuman.html', data)

    def post(self, request, id_pengumuman):
        judul = request.POST.get('judul')
        tgl_terbit = request.POST.get('tgl_terbit')
        file = request.FILES.getlist('filenya')
        isi_materi = request.POST.get('isi_materi')
        arr_file = []

        tgl_terbit_ = datetime.strptime(tgl_terbit.split(' - ')[0], '%d/%m/%Y %H:%M')
        tgl_tutup = datetime.strptime(tgl_terbit.split(' - ')[1], '%d/%m/%Y %H:%M')


        for upload_file in file:
            rand_name = re.sub('[^\w\-_\. ]', '_', encrypt(str(datetime.now())))+random_string_angka()+' - '+upload_file.name.replace(' ','')

            file_path_ = os.path.join(BASE_DIR, 'bimbel_app', 'assets', 'doc_materi_temp', rand_name)
            with open(file_path_, 'wb+') as destination:
                for chunk in upload_file.chunks():
                    destination.write(chunk)

            dbx = dropbox.Dropbox(DBX_TOKEN)
            dbx.users_get_current_account()
            with open(file_path_, 'rb') as destination:
                dbx.files_upload(bytes(destination.read()), '/pengumuman/{}'.format(rand_name))
            arr_file.append(rand_name)
            os.remove(file_path_)

        pengumuman = m_listpengumuman.objects.get(id_pengumuman = decrypt(id_pengumuman))
        pengumuman.judul = judul
        pengumuman.isi_materi = isi_materi
        pengumuman.tgl_terbit_auto = tgl_terbit_
        pengumuman.tgl_tutup_auto = tgl_tutup
        
        if len(file) != 0:
            new_arr = pengumuman.file_support
            for x in arr_file:
                new_arr.append(x)
            pengumuman.file_support = new_arr
        pengumuman.user_input = m_user.objects.get(uid=global_var(request)['uid'])
        pengumuman.save()


        return redirect('bimbel_app:edit_pengumuman', id_pengumuman = id_pengumuman)

class change_stat_pengumumanView(View):
    """docstring for change_stat_materiView"""
    def post(self, request, status_):
        id_pengumuman = decrypt(request.POST.get('xx'))
        status = False

        try:
            data_pengumuman = m_listpengumuman.objects.get(id_pengumuman = id_pengumuman)
            data_pengumuman.status = status_
            data_pengumuman.save()
            status = True
        except Exception as e:
            print(e)
            status = False

        data = {
            'status':status,
        }
        return JsonResponse(data)

class del_file_pengumumanView(View):
    """docstring for change_stat_materiView"""
    def post(self, request):
        id_pengumuman = decrypt(request.POST.get('xx'))
        nama_file = request.POST.get('aa')
        status = False

        try:
            data_pengumuman = m_listpengumuman.objects.get(id_pengumuman = id_pengumuman)
            arra_list = data_pengumuman.file_support
            arra_list.remove(nama_file)
            data_pengumuman.file_support = arra_list
            
            data_pengumuman.save()

            dbx = dropbox.Dropbox(DBX_TOKEN)
            dbx.files_delete_v2('/pengumuman/{}'.format(nama_file))
            status = True
        except Exception as e:
            print(e)
            status = False

        data = {
            'status':status,
        }
        return JsonResponse(data)

class del_pengumumanView(View):
    """docstring for change_stat_materiView"""
    def post(self, request):
        id_pengumuman = decrypt(request.POST.get('vv'))
        status = False

        try:
            data_pengumuman = m_listpengumuman.objects.get(id_pengumuman = id_pengumuman)
            if data_pengumuman.user_input.uid == global_var(request)['uid'] or global_var(request)['level'].upper() == 'ADMIN':
                for x in data_pengumuman.file_support:
                    try:
                        dbx = dropbox.Dropbox(DBX_TOKEN)
                        dbx.files_delete_v2('/pengumuman/{}'.format(x))
                    except Exception as e:
                        print(e)
                        pass
                
                data_pengumuman.delete()
            status = True
        except Exception as e:
            print(e)
            status = False

        data = {
            'status':status,
        }
        return JsonResponse(data)

class lihat_pengumumanView(View):
    """docstring for lihat_materiView"""
    def get(self, request, id_pengumuman):
        id_pengumuman = decrypt(id_pengumuman)
        data_pengumuman = m_listpengumuman.objects.get(id_pengumuman=id_pengumuman)
        data_pengumuman_ = m_listpengumuman.objects.get(id_pengumuman=id_pengumuman)
        data_pengumuman_.count_see = data_pengumuman_.count_see+1

        try:
            data_pengumuman_.save()
        except Exception as e:
            print(e)
            pass

        data = {
            'data_pengumuman':data_pengumuman,
        }
        return render(request, 'announce/lihat_pengumuman.html', data)

bimbel_app/templates/master/kategori_ujian.html
{% extends 'base/index.html' %}
{% load static %}

{% block content %}

<div class="row">
	<div class="col-8">
		<div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Kategori Ujian</h4>
			</div>
			<div class="box-body">
			  <div class="table-responsive">
				  <table id="table_user" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
					<thead>
						<tr>
							<th class="width_nomor_tabel">NO</th>
							<th>KODE UJIAN</th>
							<th>NAMA UJIAN</th>
							<th class="width_nomor_tabel"></th>
						</tr>
					</thead>
					<tbody>
						{% for x in data_ujian %}
							<tr>
								<td class="td_center">{{forloop.counter}}</td>
								<td>{{x.kode_ujian}}</td>
								<td>{{x.nama_ujian}}</td>
								<td class="td_center">
									<button class="btn btn-rounded btn-info btn-xs" onclick="edit_ujian(this)" id="btn_edit_user" data-u="{{x.nama_ujian}}" data-id="{{x.kode_ujian}}" edit_url="{% url 'bimbel_app:kategori_ujianedit' x.kode_ujian %}"><i class="fa fa-pencil"></i></button>
									<button class="btn btn-rounded btn-danger btn-xs" onclick="delete_ujian(this)" id="btn_del_user" data-u="{{x.nama_ujian}}" data-id="{{x.kode_ujian}}" del_url="{% url 'bimbel_app:kategori_ujiandelete' x.kode_ujian %}"><i class="fa fa-trash"></i></button>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				</div>       
			</div>
		</div>
	</div>
	<div class="col-4">
		<div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Input Data</h4>
			</div>
			<div class="box-body">
			  <form method="POST" action="{% url 'bimbel_app:kategori_ujian' %}" id="frm_ujian" autocomplete="off">
					{% csrf_token %}
					  <div class="form-group" id="kode_ujian_div">
					    <label for="exampleInputPassword1">Kode Ujian</label>
					      {{form.kode_ujian}}
					  </div>
					  <div class="form-group">
					      <label for="exampleInputEmail1">Nama Ujian</label>
					      {{form.nama_ujian}}
					    </div>
				  <button type="submit" class="btn btn-primary">Input</button>
				  <a href="{% url 'bimbel_app:kategori_ujian' %}" id="cancel_edit" style="display: none;" class="btn btn-danger">Cancel</a>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'js/page/kategori_ujian.js' %}"></script>
{% endblock %}

bimbel_app/templates/master/kelas.html
{% extends 'base/index.html' %}
{% load static %}

{% block content %}

<div class="row">
	<div class="col-8">
		<div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Kelas</h4>
			</div>
			<div class="box-body">
			  <div class="table-responsive">
				  <table id="table_user" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
					<thead>
						<tr>
							<th class="width_nomor_tabel">NO</th>
							<th>KODE KELAS</th>
							<th>NAMA KELAS</th>
							<th class="width_nomor_tabel"></th>
						</tr>
					</thead>
					<tbody>
						{% for x in data_kelas %}
							<tr>
								<td class="td_center">{{forloop.counter}}</td>
								<td>{{x.kode_kelas}}</td>
								<td>{{x.nama_kelas}}</td>
								<td class="td_center">
									<button class="btn btn-rounded btn-info btn-xs" onclick="edit_kelas(this)" id="btn_edit_user" data-u="{{x.nama_kelas}}" data-id="{{x.kode_kelas}}" edit_url="{% url 'bimbel_app:kelasedit' x.kode_kelas %}"><i class="fa fa-pencil"></i></button>
									<button class="btn btn-rounded btn-danger btn-xs" onclick="delete_kelas(this)" id="btn_del_user" data-u="{{x.nama_kelas}}" data-id="{{x.kode_kelas}}" del_url="{% url 'bimbel_app:kelasdelete' x.kode_kelas %}"><i class="fa fa-trash"></i></button>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				</div>       
			</div>
		</div>
	</div>
	<div class="col-4">
		<div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Input Data</h4>
			</div>
			<div class="box-body">
			  <form method="POST" action="{% url 'bimbel_app:kelas' %}" id="frm_kelas" autocomplete="off">
					{% csrf_token %}
					  <div class="form-group" id="kode_kelas_div">
					    <label for="exampleInputPassword1">Kode Kelas</label>
					      {{form.kode_kelas}}
					  </div>
					  <div class="form-group">
					      <label for="exampleInputEmail1">Nama Kelas</label>
					      {{form.nama_kelas}}
					    </div>
				  <button type="submit" class="btn btn-primary">Input</button>
				  <a href="{% url 'bimbel_app:kelas' %}" id="cancel_edit" style="display: none;" class="btn btn-danger">Cancel</a>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'js/page/kelas.js' %}"></script>
{% endblock %}

bimbel_app/templates/master/mapel.html
{% extends 'base/index.html' %}
{% load static %}

{% block content %}

<div class="row">
	<div class="col-8">
		<div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Mata Pelajaran</h4>
			</div>
			<div class="box-body">
			  <div class="table-responsive">
				  <table id="table_user" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
					<thead>
						<tr>
							<th class="width_nomor_tabel">NO</th>
							<th>KODE MAPEL</th>
							<th>NAMA MAPEL</th>
							<th class="width_nomor_tabel"></th>
						</tr>
					</thead>
					<tbody>
						{% for x in data_mapel %}
							<tr>
								<td class="td_center">{{forloop.counter}}</td>
								<td>{{x.kode_mapel}}</td>
								<td>{{x.nama_mapel.title}}</td>
								<td class="td_center">
									<button class="btn btn-rounded btn-info btn-xs" onclick="edit_mapel(this)" id="btn_edit_user" data-u="{{x.nama_mapel}}" data-id="{{x.kode_mapel}}" edit_url="{% url 'bimbel_app:mapeledit' x.kode_mapel %}"><i class="fa fa-pencil"></i></button>
									<button class="btn btn-rounded btn-danger btn-xs" onclick="delete_mapel(this)" id="btn_del_user" data-u="{{x.nama_mapel}}" data-id="{{x.kode_mapel}}" del_url="{% url 'bimbel_app:mapeldelete' x.kode_mapel %}"><i class="fa fa-trash"></i></button>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				</div>       
			</div>
		</div>
	</div>
	<div class="col-4">
		<div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Input Data</h4>
			</div>
			<div class="box-body">
			  <form method="POST" action="{% url 'bimbel_app:mapel' %}" id="frm_mapel" autocomplete="off">
					{% csrf_token %}
					  <div class="form-group" id="kode_mapel_div">
					    <label for="exampleInputPassword1">Kode Mata Pelajaran</label>
					      {{form.kode_mapel}}
					  </div>
					  <div class="form-group">
					      <label for="exampleInputEmail1">Nama Mata Pelajaran</label>
					      {{form.nama_mapel}}
					    </div>
				  <button type="submit" class="btn btn-primary">Input</button>
				  <a href="{% url 'bimbel_app:mapel' %}" id="cancel_edit" style="display: none;" class="btn btn-danger">Cancel</a>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'js/page/mapel.js' %}"></script>
{% endblock %}

bimbel_app/templates/master/usermanagement.html
{% extends 'base/index.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}

<div class="row">
	<div class="col-8">
		<div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Management User</h4>
			</div>
			<div class="box-body">
			  <div class="table-responsive">
				  <table id="table_user" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
					<thead>
						<tr>
							<th class="width_nomor_tabel">NO</th>
							<th>NAMA</th>
							<th>NIP</th>
							<th>USERNAME</th>
							<th>LEVEL</th>
							<th class="width_nomor_tabel"></th>
						</tr>
					</thead>
					<tbody>
						{% for x in data_user %}
							<tr>
								<td class="td_center">{{forloop.counter}}</td>
								<td>{{x.fullname.title}}</td>
								<td>{{x.nip}}</td>
								<td>{{x.uname}}</td>
								<td>{{x.level}}</td>
								<td class="td_center">
									<button class="btn btn-rounded btn-info btn-xs" onclick="edit_user(this)" id="btn_edit_user" data-u="{{x.uname}}" data-id="{{x.uid|encrypt_this}}" edit_url="{% url 'bimbel_app:usermanagementedit' x.uid|encrypt_this %}"><i class="fa fa-pencil"></i></button>
									<button class="btn btn-rounded btn-danger btn-xs" onclick="delete_user(this)" id="btn_del_user" data-u="{{x.uname}}" data-id="{{x.uid|encrypt_this}}" del_url="{% url 'bimbel_app:usermanagementdelete' x.uid|encrypt_this %}"><i class="fa fa-trash"></i></button>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				</div>       
			</div>
		</div>
	</div>
	<div class="col-4">
		<div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Input Data</h4>
			</div>
			<div class="box-body">
			  <form method="POST" action="{% url 'bimbel_app:usermanagement' %}" id="frm_user" autocomplete="off">
					{% csrf_token %}
					  <div class="form-group">
					    <label for="exampleInputPassword1">NIP</label>
					    {{form.nip}}
					  </div>
					  <div class="form-group">
					      <label for="exampleInputEmail1">Nama Lengkap</label>
					      {{form.fullname}}
					    </div>
				  <div class="form-group">
				    <label for="exampleInputPassword1">Hakakses</label>
				    {{form.level}}
				  </div>
					<div class="form-group">
				      <label for="exampleInputEmail1">Username</label>
				      {{form.uname}}
				    </div>
				    <div class="form-group" id="div_pwd">
				      <label for="exampleInputPassword1">Password</label>
				      {{form.pwd}}
				    </div>
				  <button type="submit" class="btn btn-primary">Input</button>
				  <a href="{% url 'bimbel_app:usermanagement' %}" id="cancel_edit" style="display: none;" class="btn btn-danger">Cancel</a>
				</form>
			</div>
			<!-- /.box-body -->
			<!-- <div class="box-footer">
			  <button type="submit" class="btn btn-rounded btn-success">Input</button><button class="btn btn-rounded btn-danger">Cancel</button>
			</div> -->
			<!-- /.box-footer-->
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'js/page/usermanagement.js' %}"></script>
{% endblock %}