bimbel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('dash/', include('bimbel_app.urls')),
]
urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bimbel_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import base_views
from .views import master_views
from .views import kesiswaan_views
from .views import ujian_views
from .views import materi_views
from .views import guru_views
from .views import announce_views
# from .views import penimbangan_views
# from .views import nota_views

app_name = 'bimbel_app'
urlpatterns = [
    path('', base_views.IndexView.as_view(), name = 'index'),
    path('login/', base_views.LoginView.as_view(), name = 'login'),
    path('logout/', base_views.LogoutView.as_view(), name = 'logout'),
    path('pengaturan/aplikasi/', base_views.setting_aplikasiView.as_view(), name = 'setting_aplikasi'),
    # path('join_video_conf/', base_views.join_video_confView.as_view(), name = 'join_video_conf'),
    path('master/usermanagement/', master_views.UsermanagementView.as_view(), name = 'usermanagement'),
    path('master/usermanagement/edit/<str:uid>/', master_views.UsermanagementEditView.as_view(), name = 'usermanagementedit'),
    path('master/usermanagement/delete/<str:uid>/', master_views.UsermanagementDeleteView.as_view(), name = 'usermanagementdelete'),

    path('master/mapel/', master_views.MapelView.as_view(), name = 'mapel'),
    path('master/mapel/edit/<str:kode_mapel>/', master_views.MapelEditView.as_view(), name = 'mapeledit'),
    path('master/mapel/delete/<str:kode_mapel>/', master_views.MapelDeleteView.as_view(), name = 'mapeldelete'),

    path('master/kelas/', master_views.KelasView.as_view(), name = 'kelas'),
    path('master/kelas/edit/<str:kode_kelas>/', master_views.KelasEditView.as_view(), name = 'kelasedit'),
    path('master/kelas/delete/<str:kode_kelas>/', master_views.KelasDeleteView.as_view(), name = 'kelasdelete'),

    path('master/kategori-ujian/', master_views.kategori_ujianView.as_view(), name = 'kategori_ujian'),
    path('master/kategori_ujian/edit/<str:kode_ujian>/', master_views.kategori_ujianEditView.as_view(), name = 'kategori_ujianedit'),
    path('master/kategori_ujian/delete/<str:kode_ujian>/', master_views.kategori_ujianDeleteView.as_view(), name = 'kategori_ujiandelete'),

    path('kesiswaan/pesertadidik/', kesiswaan_views.PesertaDidikView.as_view(), name = 'pesertadidik'),
    path('kesiswaan/pesertadidik/<str:type_>/<int:uid>/', kesiswaan_views.tambah_siswaView.as_view(), name = 'tambah_siswa'),
    path('kesiswaan/profil-pesertadidik/<str:type_>/<str:uid>/', kesiswaan_views.profil_siswaView.as_view(), name = 'profil_siswa'),
    path('kesiswaan/pesertadidik/<int:uid>/', kesiswaan_views.DeleteSiswaViews.as_view(), name = 'hapus_siswa'),
    path('kesiswaan/pesertadidik/validation/access-login/vali_log/', kesiswaan_views.ValidationLoginSiswaViews.as_view(), name = 'vali_log'),

    path('pengajar/guru/', guru_views.guruView.as_view(), name = 'guru'),
    path('pengajar/guru/<str:type_>/<int:uid>/', guru_views.tambah_guruView.as_view(), name = 'tambah_guru'),

    path('pengajar/profil-guru/<str:type_>/<str:uid>/', guru_views.profil_guruView.as_view(), name = 'profil_guru'),

    path('ujian/list_ujian/', ujian_views.List_ujianView.as_view(), name = 'list_ujian'),
    path('ujian/list_ujian/add_edit/<str:type_>/<str:uid>/', ujian_views.tambah_ujianView.as_view(), name = 'tambah_ujian'),
    path('ujian/list_ujian/delete/<str:uid>/', ujian_views.DeleteListUjianViews.as_view(), name = 'list_ujiandelete'),
    path('ujian/list_ujian/manajemen_soal/<str:uid>/', ujian_views.manajemen_soal_ujianView.as_view(), name = 'manajemen_soal_ujian'),
    path('ujian/list_ujian/upload_image_soal/', ujian_views.upload_image_soalViews.as_view(), name = 'upload_image_soal'),
    path('ujian/list_ujian/get_soal/', ujian_views.get_soalViews.as_view(), name = 'get_soal'),
    path('ujian/list_ujian/assignment/<str:id_ujian>/', ujian_views.kerjakan_soalViews.as_view(), name = 'kerjakan_soal'),
    path('ujian/list_ujian/get_soal_/', ujian_views.get_soaldankunciViews.as_view(), name = 'get_soaldankunci'),
    path('ujian/list_ujian/check_jawaban/', ujian_views.check_jawabanViews.as_view(), name = 'check_jawaban'),
    path('ujian/list_ujian/force_empty/', ujian_views.force_emptyViews.as_view(), name = 'force_empty'),
    path('ujian/lihat_hasil/<str:id_ujian>/', ujian_views.Lihat_hasilViews.as_view(), name = 'lihat_hasil'),
    path('ujian/change_stat_ujian/<str:status_>/', ujian_views.change_stat_ujianView.as_view(), name = 'change_stat_ujian'),
    path('ujian/peserta_ujian/<str:id_ujian>/', ujian_views.peserta_ujianView.as_view(), name = 'peserta_ujian'),

    path('materi/list_materi/', materi_views.List_materiView.as_view(), name = 'list_materi'),
    path('materi/create_materi/', materi_views.Create_materiView.as_view(), name = 'create_materi'),
    path('materi/change_stat_materi/<str:status_>/', materi_views.change_stat_materiView.as_view(), name = 'change_stat_materi'),
    path('materi/del_materi/', materi_views.del_materiView.as_view(), name = 'del_materi'),
    path('materi/edit_materi/<str:id_materi>/', materi_views.Edit_materiView.as_view(), name = 'edit_materi'),
    path('materi/del_fileView/', materi_views.del_fileView.as_view(), name = 'del_file'),
    path('materi/lihat_materi/<str:id_materi>/', materi_views.lihat_materiView.as_view(), name = 'lihat_materi'),
    
    path('pengumuman/daftar_pengumuman/', announce_views.list_announceViews.as_view(), name = 'list_announce'),
    path('pengumuman/create_pengumuman/', announce_views.Create_pengumumanView.as_view(), name = 'create_pengumuman'),
    path('pengumuman/edit_pengumuman/<str:id_pengumuman>/', announce_views.Edit_pengumumanView.as_view(), name = 'edit_pengumuman'),
    path('pengumuman/del_fileView/', announce_views.del_file_pengumumanView.as_view(), name = 'del_file_pengumuman'),
    path('pengumuman/change_stat_pengumuman/<str:status_>/', announce_views.change_stat_pengumumanView.as_view(), name = 'change_stat_pengumuman'),
    path('pengumuman/lihat_pengumuman/<str:id_pengumuman>/', announce_views.lihat_pengumumanView.as_view(), name = 'lihat_pengumuman'),
    path('pengumuman/del_pengumuman/', announce_views.del_pengumumanView.as_view(), name = 'del_pengumuman'),
] 

bimbel_app/views/announce_views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
import json, os, requests
from django.contrib import messages
from bimbel_app.models.master import (Master_user as m_user, Master_mata_pelajaran as m_mapel, Peserta_didik as m_pd, 
                                        Master_kelas as m_kelas, List_ujian as m_listujian, Master_ujian as m_ujian, Manajemen_soal as m_soal,
                                        Jawaban_soal as j_soal, Siswa_assignment as s_assignment, List_materi as m_listmateri,
                                        List_pengumuman as m_listpengumuman)
from django.forms import *
from support.support_function import decrypt, encrypt, global_var, random_string_angka
from bimbel.settings import BASE_DIR, DBX_TOKEN
import re
from datetime import datetime
from django.db.models import Q
from django.template import RequestContext
import dropbox
from django.urls import reverse
from bimbel_app.views.ujian_views import Helper

class list_announceViews(View):
    """docstring for List_ujianView"""
    def get(self, request):
        if global_var(request)['level'] == 'GURU':
            data_pengumuman = m_listpengumuman.objects.filter(user_input = global_var(request)['uid'])
        elif global_var(request)['level'] == 'ADMIN':
            data_pengumuman = m_listpengumuman.objects.all()
        else:
            data_pengumuman = ''
        data = {
            'data_pengumuman':data_pengumuman,
        }
        return render(request, 'announce/list_pengumuman.html', data)

class Create_pengumumanView(View):
    """docstring for Create_materiView"""
    def get(self, request):
        data_kelas = m_kelas.objects.all()
        data_jenis_ujian = m_ujian.objects.all()
        data_mapel = m_mapel.objects.all()
        data_list_ujian = ''
        data_login = ''
        uuid = 0
        
        data = {
            'data_kelas':data_kelas,
            # 'type_':type_, 
            'data_list_ujian':data_list_ujian,
            'data_login':data_login,
            # 'uuid':uid,
            'data_jenis_ujian':data_jenis_ujian,
            'data_mapel':data_mapel,
            'link':reverse('bimbel_app:create_pengumuman'),
        }
        return render(request, 'announce/create_pengumuman.html', data)

    def post(self, request):
        judul = request.POST.get('judul')
        tgl_terbit = request.POST.get('tgl_terbit')
        file = request.FILES.getlist('filenya')
        isi_materi = request.POST.get('isi_materi')
        arr_file = []

        tgl_terbit_ = datetime.strptime(tgl_terbit.split(' - ')[0], '%d/%m/%Y %H:%M')
        tgl_tutup = datetime.strptime(tgl_terbit.split(' - ')[1], '%d/%m/%Y %H:%M')


        for upload_file in file:
            rand_name = re.sub('[^\w\-_\. ]', '_', encrypt(str(datetime.now())))+random_string_angka()+' - '+upload_file.name.replace(' ','')

            file_path_ = os.path.join(BASE_DIR, 'bimbel_app', 'assets', 'doc_materi_temp', rand_name)
            with open(file_path_, 'wb+') as destination:
                for chunk in upload_file.chunks():
                    destination.write(chunk)

            dbx = dropbox.Dropbox(DBX_TOKEN)
            dbx.users_get_current_account()
            with open(file_path_, 'rb') as destination:
                dbx.files_upload(bytes(destination.read()), '/pengumuman/{}'.format(rand_name))
            arr_file.append(rand_name)
            os.remove(file_path_)

        pengumuman = m_listpengumuman(
                judul = judul,
                isi_materi = isi_materi,
                status = 'TERBIT',
                tgl_terbit_auto = tgl_terbit_,
                tgl_tutup_auto = tgl_tutup,
                file_support = arr_file,
                user_input = m_user.objects.get(uid=global_var(request)['uid']),
                count_see = 0,
            )
        pengumuman.save()

        last_id_ = m_listpengumuman.objects.latest('id_pengumuman')

        return redirect('bimbel_app:edit_pengumuman', id_pengumuman=encrypt(str(last_id_.id_pengumuman)))

class Edit_pengumumanView(View):
    """docstring for Create_materiView"""
    def get(self, request, id_pengumuman):
        id_pengumuman = decrypt(id_pengumuman)
        data_kelas = m_kelas.objects.all()
        data_jenis_ujian = m_ujian.objects.all()
        data_mapel = m_mapel.objects.all()
        data_pengumuman = m_listpengumuman.objects.get(id_pengumuman = id_pengumuman)
        data_list_ujian = ''
        data_login = ''
        uuid = 0
        
        data = {
            'data_kelas':data_kelas,
            'type_':'edit', 
            'data_list_ujian':data_list_ujian,
            'data_login':data_login,
            # 'uuid':uid,
            'data_jenis_ujian':data_jenis_ujian,
            'data_mapel':data_mapel,
            'data_pengumuman':data_pengumuman,
            'link':reverse('bimbel_app:edit_pengumuman', args=(encrypt(id_pengumuman),)),
        }
        return render(request, 'announce/create_pengumuman.html', data)

    def post(self, request, id_pengumuman):
        judul = request.POST.get('judul')
        tgl_terbit = request.POST.get('tgl_terbit')
        file = request.FILES.getlist('filenya')
        isi_materi = request.POST.get('isi_materi')
        arr_file = []

        tgl_terbit_ = datetime.strptime(tgl_terbit.split(' - ')[0], '%d/%m/%Y %H:%M')
        tgl_tutup = datetime.strptime(tgl_terbit.split(' - ')[1], '%d/%m/%Y %H:%M')


        for upload_file in file:
            rand_name = re.sub('[^\w\-_\. ]', '_', encrypt(str(datetime.now())))+random_string_angka()+' - '+upload_file.name.replace(' ','')

            file_path_ = os.path.join(BASE_DIR, 'bimbel_app', 'assets', 'doc_materi_temp', rand_name)
            with open(file_path_, 'wb+') as destination:
                for chunk in upload_file.chunks():
                    destination.write(chunk)

            dbx = dropbox.Dropbox(DBX_TOKEN)
            dbx.users_get_current_account()
            with open(file_path_, 'rb') as destination:
                dbx.files_upload(bytes(destination.read()), '/pengumuman/{}'.format(rand_name))
            arr_file.append(rand_name)
            os.remove(file_path_)

        pengumuman = m_listpengumuman.objects.get(id_pengumuman = decrypt(id_pengumuman))
        pengumuman.judul = judul
        pengumuman.isi_materi = isi_materi
        pengumuman.tgl_terbit_auto = tgl_terbit_
        pengumuman.tgl_tutup_auto = tgl_tutup
        
        if len(file) != 0:
            new_arr = pengumuman.file_support
            for x in arr_file:
                new_arr.append(x)
            pengumuman.file_support = new_arr
        pengumuman.user_input = m_user.objects.get(uid=global_var(request)['uid'])
        pengumuman.save()


        return redirect('bimbel_app:edit_pengumuman', id_pengumuman = id_pengumuman)

class change_stat_pengumumanView(View):
    """docstring for change_stat_materiView"""
    def post(self, request, status_):
        id_pengumuman = decrypt(request.POST.get('xx'))
        status = False

        try:
            data_pengumuman = m_listpengumuman.objects.get(id_pengumuman = id_pengumuman)
            data_pengumuman.status = status_
            data_pengumuman.save()
            status = True
        except Exception as e:
            print(e)
            status = False

        data = {
            'status':status,
        }
        return JsonResponse(data)

class del_file_pengumumanView(View):
    """docstring for change_stat_materiView"""
    def post(self, request):
        id_pengumuman = decrypt(request.POST.get('xx'))
        nama_file = request.POST.get('aa')
        status = False

        try:
            data_pengumuman = m_listpengumuman.objects.get(id_pengumuman = id_pengumuman)
            arra_list = data_pengumuman.file_support
            arra_list.remove(nama_file)
            data_pengumuman.file_support = arra_list
            
            data_pengumuman.save()

            dbx = dropbox.Dropbox(DBX_TOKEN)
            dbx.files_delete_v2('/pengumuman/{}'.format(nama_file))
            status = True
        except Exception as e:
            print(e)
            status = False

        data = {
            'status':status,
        }
        return JsonResponse(data)

class del_pengumumanView(View):
    """docstring for change_stat_materiView"""
    def post(self, request):
        id_pengumuman = decrypt(request.POST.get('vv'))
        status = False

        try:
            data_pengumuman = m_listpengumuman.objects.get(id_pengumuman = id_pengumuman)
            if data_pengumuman.user_input.uid == global_var(request)['uid'] or global_var(request)['level'].upper() == 'ADMIN':
                for x in data_pengumuman.file_support:
                    try:
                        dbx = dropbox.Dropbox(DBX_TOKEN)
                        dbx.files_delete_v2('/pengumuman/{}'.format(x))
                    except Exception as e:
                        print(e)
                        pass
                
                data_pengumuman.delete()
            status = True
        except Exception as e:
            print(e)
            status = False

        data = {
            'status':status,
        }
        return JsonResponse(data)

class lihat_pengumumanView(View):
    """docstring for lihat_materiView"""
    def get(self, request, id_pengumuman):
        id_pengumuman = decrypt(id_pengumuman)
        data_pengumuman = m_listpengumuman.objects.get(id_pengumuman=id_pengumuman)
        data_pengumuman_ = m_listpengumuman.objects.get(id_pengumuman=id_pengumuman)
        data_pengumuman_.count_see = data_pengumuman_.count_see+1

        try:
            data_pengumuman_.save()
        except Exception as e:
            print(e)
            pass

        data = {
            'data_pengumuman':data_pengumuman,
        }
        return render(request, 'announce/lihat_pengumuman.html', data)

bimbel_app/templates/materi/lihat_materi.html
{% extends 'base/index.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
<style type="text/css">
	.custom_width{
		width: 3em !important;
	}
</style>
<div class="row">
	<div class="col-4">
		<div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Detail Materi</h4>
			</div>
			<div class="box-body">
			  <div class="row">
			  	<div class="col-md-3">
			  		Judul
			  	</div>
			  	<div class="col-md-8">
			  		: {{data_materi.judul}}
			  	</div>
			  </div>
			  <div class="row">
			  	<div class="col-md-3">
			  		MAPEL
			  	</div>
			  	<div class="col-md-8">
			  		: {{data_materi.mata_pelajaran.nama_mapel}}
			  	</div>
			  </div>
			  <div class="row">
			  	<div class="col-md-3">
			  		Creator
			  	</div>
			  	<div class="col-md-8">
			  		: {{data_materi.user_input.fullname}}
			  	</div>
			  </div>
			  <div class="row">
			  	<div class="col-md-3">
			  		File Pendukung
			  	</div>
			  	<div class="col-md-8">
			  		:  {{data_materi.file_support|length}} File
			  	</div>
			  </div>
			  <div class="row mt-35">
				  	<div class="col-12">
				  		 <div class="media-list media-list-divided">
				  		 	{% for xx in data_materi.file_support %}
							<div class="media media-single px-0" id="mediasupport_{{forloop.counter}}">
							  <div class="ml-0 mr-15 bg-primary-light h-50 w-50 l-h-50 rounded text-center">
							    <span class="font-size-24 text-primary"><i class="fa fa-file-text"></i></span>
							  </div>
							  <span class="title font-weight-500 font-size-16" data-toggle="tooltip" title="{{xx|get_filename}}" style="cursor: pointer;">{{xx|get_filename|slice:":35"}}</span>
							  <a class="font-size-18 text-gray hover-info btn btn-info" href="{{xx|get_link_dbx_file}}"><i class="fa fa-download"></i></a>
							</div>
							{% endfor %}
						  </div>
				  	</div>
				</div>
			</div>
		</div>
	</div>

	<div class="col-8">
			<input type="hidden" name="soalke" id="soalke" value="{{xx.no_soal}}">
			<input type="hidden" name="id_soal_" id="id_soal_" value="">
			<div class="box">
				<div class="box-header with-border">
				  <h4 class="box-title">Materi</span></h4>
				</div>
				<div class="box-body">
					<div class="row mb-10">
						<div class="col-12 mb-10">
							<div id="soal">
								{{data_materi.isi_materi | safe}}
							</div>
						</div>
					</div>
				</div>
			</div>
	</div>
</div>

{% endblock %}
{% block js %}
<script src="{% static 'vendor_components/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript">

	$(document).ready(function(){
		$('#table_user').DataTable( {
			sort:false,
			dom: 'Bfrtip',
			buttons: [
				'excel', 'pdf'
			]
		} );
	})

	let editor;

	ClassicEditor
	    .create( document.querySelector( '#soal' ), {
	        // ...
	        toolbar: [],
	    } )
	    .then( newEditor => {
	        editor = newEditor;
	        editor.isReadOnly = true;
	    } )
	    .catch( error => {
	        console.log( error );
	    } );
</script>
{% endblock %}

bimbel_app/templates/materi/list_materi.html
{% extends 'base/index.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}

<div class="row">
	<div class="col-12">
		<div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Daftar Materi <a class="btn btn-md btn-primary" href="{% url 'bimbel_app:create_materi' %}">Buat Materi</a></h4>
			</div>
			<div class="box-body">
			  <div class="table-responsive">
				  <table id="table_user" class="table table-bordered table-hover display wrap margin-top-10 w-p100">
					<thead>
						<tr>
							<th class="width_nomor_tabel td_center">NO</th>
							<th class="td_center">JUDUL</th>
							<th class="td_center">MATA PELAJARAN</th>
							<th class="td_center">KELAS</th>
							<th class="width_nomor_tabel td_center">STATUS</th>
							<th class="width_nomor_tabel"></th>
						</tr>
					</thead>
					<tbody>
						{% for x in data_materi %}
							<tr>
								<td class="td_center">{{forloop.counter}}</td>
								<td>{{x.judul}}</td>
								<td>{{x.mata_pelajaran.nama_mapel}}</td>
								{% if x.kelas == 'all' %}
									<td>Semua Kelas</td>
								{% elif x.kelas == 'except' %}
									<td>Semua Kelas Kecuali : {% for xx in x.daftar_kelas|get_nama_kelas %} {% if not forloop.last %} {{xx}}, {% else %} {{xx}} {% endif %} {% endfor %}</td>
								{% else %}
									<td>{% for xx in x.daftar_kelas|get_nama_kelas %} {% if not forloop.last %} {{xx}}, {% else %} {{xx}} {% endif %} {% endfor %}</td>
								{% endif %}
								<td class="td_center">
									{% if x.status.upper == 'TUTUP' %}<span id="status_{{forloop.counter}}" class="badge badge-danger">{{x.status.upper}}</span>
									{% elif x.status.upper == 'TERBIT' %}<span id="status_{{forloop.counter}}" class="badge badge-success">{{x.status.upper}}</span>
									{% endif %}
								</td>
								<td class="td_center">
									<div class="btn-group">
									  <button class="btn btn-xs btn-dark dropdown-toggle" type="button" data-toggle="dropdown">Aksi</button>
									  <div class="dropdown-menu dropdown-menu-right">
									  	<a class="dropdown-item" href="{% url 'bimbel_app:lihat_materi' x.id_materi|encrypt_this %}">Lihat</a>
										<a class="dropdown-item" href="{% url 'bimbel_app:edit_materi' x.id_materi|encrypt_this %}">Perbarui</a>
										{% if x.status == 'TERBIT' %}
											<a class="dropdown-item" href="#" link_="{% url 'bimbel_app:change_stat_materi' 'TUTUP' %}" ext="{{forloop.counter}}" onclick="change_stat(this, '{{x.id_materi|encrypt_this}}')">Tutup Sementara</a>
										{% else %}
											<a class="dropdown-item" href="#" link_="{% url 'bimbel_app:change_stat_materi' 'TERBIT' %}" ext="{{forloop.counter}}" onclick="change_stat(this, '{{x.id_materi|encrypt_this}}')">Buka</a>
										{% endif %}
										<a class="dropdown-item" href="#" onclick="delete_materi(this, '{{x.id_materi|encrypt_this}}')" data-u="{{x.judul}}" data-vv="{{x.id_materi|encrypt_this}}" link_="{% url 'bimbel_app:del_materi' %}">Hapus</a>
									  </div>
									</div>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				</div>       
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
	$(document).ready(function(){
		$('#table_user').DataTable( {
		sort:false,
		dom: 'Bfrtip',
		buttons: [
			
		]
	} );

		
	})

	function change_stat(e, xx){
		$.ajax({
            type: "POST",
            headers: { "X-CSRFToken": csrf_token },
            url: $(e).attr('link_'),
            data: {'xx':xx},
            dataType: 'json',
            success: function(res){
                if (res['status']) {
                    msg_pesan('Ubah Status Sukses. ','success');
                    if ($(e).text() == 'Tutup Sementara') {
                    	$(e).text('Buka');
                    	$('#status_'+$(e).attr('ext')+'').text('TUTUP');
                    	$('#status_'+$(e).attr('ext')+'').removeClass('badge-success');
                    	$('#status_'+$(e).attr('ext')+'').addClass('badge-danger');
                    }else{
                    	$(e).text('Tutup Sementara');
                    	$('#status_'+$(e).attr('ext')+'').text('TERBIT');
                    	$('#status_'+$(e).attr('ext')+'').removeClass('badge-danger');
                    	$('#status_'+$(e).attr('ext')+'').addClass('badge-success');
                    }
                }else{
                	msg_pesan('Ubah Status Gagal','error');
                }
            },
            error: function(res){
                msg_pesan('Ubah Status Gagal. Hubungi Administrator','error');
            }
        });
	}

	function delete_materi(e){
		Swal.fire({
              title: 'Ingin Menghapus \n \"'+$(e).attr('data-u')+'\" ?',
              icon: 'warning',
              showCancelButton: true,
              confirmButtonColor: '#3085d6',
              cancelButtonColor: '#d33',
              confirmButtonText: 'Hapus'
            }).then((result) => {
              if (result.isConfirmed) {
                $.ajax({
                    type: "POST",
                    headers: { "X-CSRFToken": csrf_token },
                    url: $(e).attr('link_'),
                    data: {'vv':$(e).attr('data-vv')},
                    dataType: 'json',
                    success: function(res){
                        if (res['status']) {
                            msg_pesan('Hapus Materi Sukses. ','success');
                            location.reload();
                        }else{
                        	if (res['protected']) {
                            	msg_pesan('Hapus Materi Gagal. ','error');
                        	}else{
                            	msg_pesan('HHapus Materi Gagal Hubungi Administrator. ','error');
                        	}
                        }
                    },
                    error: function(res){
                        msg_pesan('Hapus Ujian Gagal. ','error');
                    }
                });
              }
            });
	};
</script>
{% endblock %}